version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10
    parallelism: 4
    steps:
      - checkout
      - run: npm ci --production
      - run: npm run test-js
      - run: npm run test-css
